USE [master]
GO

/****** Object:  Database [Paint]    Script Date: 5/13/2022 6:11:00 PM ******/
CREATE DATABASE [Paint]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Paint', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Paint.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Paint_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Paint_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Paint].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Paint] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Paint] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Paint] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Paint] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Paint] SET ARITHABORT OFF 
GO

ALTER DATABASE [Paint] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Paint] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Paint] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Paint] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Paint] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Paint] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Paint] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Paint] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Paint] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Paint] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Paint] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Paint] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Paint] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Paint] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Paint] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Paint] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Paint] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Paint] SET RECOVERY FULL 
GO

ALTER DATABASE [Paint] SET  MULTI_USER 
GO

ALTER DATABASE [Paint] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Paint] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Paint] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Paint] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Paint] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Paint] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Paint] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Paint] SET  READ_WRITE 
GO


